Hw 1
Terlog/hillel_hw pull request #1
Opened 2022-02-12 17:36 UTC by Terlog

2022-02-15 13:04 UTC, fo0lman requested changes
в целом ок
Поправить 
1й коммит добавить пустые строки в конце
2й все остальные замечания

2022-02-15 13:04 UTC, fo0lman commented on hw-2/MyResume/index.html
> +</html>
Добавить в конце каждого файла пустую строку, гх ругается
![image](https://user-images.githubusercontent.com/9566996/154067275-2bbd29f6-ffc5-4f17-8163-ecaa3d0c6632.png)

2022-02-15 13:04 UTC, fo0lman commented on hw-3/pages/autorisation.html
> +        </menu>
лучше так уже не делать menu устаревшее

2022-02-15 13:04 UTC, fo0lman commented on hw-3/pages/go.html
> +
убирать все пустые строки во всех файлах

2022-02-15 22:09 UTC, Terlog commented on hw-2/MyResume/index.html
> +</html>
поправил во всех файлах

2022-02-15 22:11 UTC, Terlog commented on hw-3/pages/autorisation.html
> +        </menu>
заменил тег <menu> на  <address>  - как более адекватный по моему мнению ,в данной ситуации

2022-02-15 22:11 UTC, Terlog commented on hw-3/pages/go.html
> +
убрал во всех файлах

2022-02-16 09:23 UTC, fo0lman requested changes

2022-02-16 09:23 UTC, fo0lman commented on hw-3/index.html
> +        </address>
нет li только в ul ol

2022-02-16 09:23 UTC, fo0lman commented on hw-3/pages/autorisation.html
> +        </address>
не верно

2022-02-16 09:23 UTC, fo0lman commented on hw-3/pages/go.html
> +        </address>
и тут

2022-02-16 09:23 UTC, fo0lman commented on hw-3/pages/reg.html
> +        </address>
ну и тут

2022-02-16 18:50 UTC, fo0lman approved these changes

2022-02-16 18:50 UTC, fo0lman commented
```*``` main
git fetch
git pull

2022-02-16 18:51 UTC, merged